/*
 * colores.h
 * definiciones de la paleta de colores de 16 bits
 * Febrero 19, 2015
 * Eduardo Alvarez Lopez
 */

//-----------------------------------------------------------------------------------//
//------------------------ Definiciones de Colores de 16 bit ------------------------//
//-----------------------------------------------------------------------------------//
#ifndef COLORES_H_		// comprueba sino se ha definido ya esta libreria para evitar errores
	#define COLORES_H_	//de compilacion y sino se ha definido lo define

#include "definicionesvar.h"
	#define COLOR_ALICEBLUE		0xF7DF
	#define COLOR_ANTIQUEWHITE	0xFF5A
	#define COLOR_AQUA			0x07FF
	#define COLOR_AQUAMARINE	0x7FFA
	#define COLOR_AZURE			0xF7FF
	#define COLOR_BEIGE			0xF7BB
	#define COLOR_BISQUE		0xFF38
	#define COLOR_BLACK 		0x0000
	#define COLOR_BLANCHEDALMOND 0xFF59
	#define COLOR_BLUE 			0x001F
	#define COLOR_BLUEVIOLET 	0x895C
	#define COLOR_BROWN 		0xA145
	#define COLOR_BURLYWOOD 	0xDDD0
	#define COLOR_CADETBLUE 	0x5CF4
	#define COLOR_CHARTREUSE 	0x7FE0
	#define COLOR_CHOCOLATE 	0xD343
	#define COLOR_CORAL 		0xFBEA
	#define COLOR_CORNFLOWERBLUE 0x64BD
	#define COLOR_CORNSILK 		0xFFDB
	#define COLOR_CRIMSON 		0xD8A7
	#define COLOR_CYAN 			0x07FF
	#define COLOR_DARKBLUE 		0x0011
	#define COLOR_DARKCYAN 		0x0451
	#define COLOR_DARKGOLDENROD 0xBC21
	#define COLOR_DARKGRAY 		0xAD55
	#define COLOR_DARKGREEN 	0x0320
	#define COLOR_DARKKHAKI 	0xBDAD
	#define COLOR_DARKMAGENTA 	0x8811
	#define COLOR_DARKOLIVEGREEN 0x5345
	#define COLOR_DARKORANGE 	0xFC60
	#define COLOR_DARKORCHID 	0x9999
	#define COLOR_DARKRED 		0x8800
	#define COLOR_DARKSALMON 	0xECAF
	#define COLOR_DARKSEAGREEN 	0x8DF1
	#define COLOR_DARKSLATEBLUE 0x49F1
	#define COLOR_DARKSLATEGRAY 0x2A69
	#define COLOR_DARKTURQUOISE 0x067A
	#define COLOR_DARKVIOLET 	0x901A
	#define COLOR_DEEPPINK 		0xF8B2
	#define COLOR_DEEPSKYBLUE 	0x05FF
	#define COLOR_DIMGRAY 		0x6B4D
	#define COLOR_DODGERBLUE 	0x1C9F
	#define COLOR_FIREBRICK 	0xB104
	#define COLOR_FLORALWHITE 	0xFFDE
	#define COLOR_FORESTGREEN 	0x2444
	#define COLOR_FUCHSIA 		0xF81F
	#define COLOR_GAINSBORO 	0xDEFB
	#define COLOR_GHOSTWHITE 	0xFFDF
	#define COLOR_GOLD 			0xFEA0
	#define COLOR_GOLDENROD 	0xDD24
	#define COLOR_GRAY 			0x8410
	#define COLOR_GREEN 		0x0400
	#define COLOR_GREENYELLOW 	0xAFE5
	#define COLOR_HONEYDEW 		0xF7FE
	#define COLOR_HOTPINK 		0xFB56
	#define COLOR_INDIANRED 	0xCAEB
	#define COLOR_INDIGO 		0x4810
	#define COLOR_IVORY 		0xFFFE
	#define COLOR_KHAKI 		0xF731
	#define COLOR_LAVENDER 		0xE73F
	#define COLOR_LAVENDERBLUSH 0xFF9E
	#define COLOR_LAWNGREEN 	0x7FE0
	#define COLOR_LEMONCHIFFON 	0xFFD9
	#define COLOR_LIGHTBLUE 	0xAEDC
	#define COLOR_LIGHTCORAL 	0xF410
	#define COLOR_LIGHTCYAN 	0xE7FF
	#define COLOR_LIGHTGOLDENRODYELLOW 0xFFDA
	#define COLOR_LIGHTGREEN 	0x9772
	#define COLOR_LIGHTGREY 	0xD69A
	#define COLOR_LIGHTPINK 	0xFDB8
	#define COLOR_LIGHTSALMON 	0xFD0F
	#define COLOR_LIGHTSEAGREEN 0x2595
	#define COLOR_LIGHTSKYBLUE 	0x867F
	#define COLOR_LIGHTSLATEGRAY 0x7453
	#define COLOR_LIGHTSTEELBLUE 0xB63B
	#define COLOR_LIGHTYELLOW 	0xFFFC
	#define COLOR_LIME 			0x07E0
	#define COLOR_LIMEGREEN 	0x3666
	#define COLOR_LINEN 		0xFF9C
	#define COLOR_MAGENTA 		0xF81F
	#define COLOR_MAROON 		0x8000
	#define COLOR_MEDIUMAQUAMARINE 0x6675
	#define COLOR_MEDIUMBLUE 	0x0019
	#define COLOR_MEDIUMORCHID 	0xBABA
	#define COLOR_MEDIUMPURPLE 	0x939B
	#define COLOR_MEDIUMSEAGREEN	0x3D8E
	#define COLOR_MEDIUMSLATEBLUE	0x7B5D
	#define COLOR_MEDIUMSPRINGGREEN	0x07D3
	#define COLOR_MEDIUMTURQUOISE	0x4E99
	#define COLOR_MEDIUMVIOLETRED	0xC0B0
	#define COLOR_MIDNIGHTBLUE 	0x18CE
	#define COLOR_MINTCREAM 	0xF7FF
	#define COLOR_MISTYROSE 	0xFF3C
	#define COLOR_MOCCASIN 		0xFF36
	#define COLOR_NAVAJOWHITE 	0xFEF5
	#define COLOR_NAVY			0x0010
	#define COLOR_OLDLACE 		0xFFBC
	#define COLOR_OLIVE 		0x8400
	#define COLOR_OLIVEDRAB 	0x6C64
	#define COLOR_ORANGE 		0xFD20
	#define COLOR_ORANGERED 	0xFA20
	#define COLOR_ORCHID 		0xDB9A
	#define COLOR_PALEGOLDENROD 0xEF55
	#define COLOR_PALEGREEN 	0x9FD3
	#define COLOR_PALETURQUOISE 0xAF7D
	#define COLOR_PALEVIOLETRED 0xDB92
	#define COLOR_PAPAYAWHIP 	0xFF7A
	#define COLOR_PEACHPUFF 	0xFED7
	#define COLOR_PERU 			0xCC27
	#define COLOR_PINK 			0xFE19
	#define COLOR_PLUM 			0xDD1B
	#define COLOR_POWDERBLUE 	0xB71C
	#define COLOR_PURPLE 		0x8010
	#define COLOR_RED 			0xF800
	#define COLOR_ROSYBROWN 	0xBC71
	#define COLOR_ROYALBLUE 	0x435C
	#define COLOR_SADDLEBROWN 	0x8A22
	#define COLOR_SALMON 		0xFC0E
	#define COLOR_SANDYBROWN 	0xF52C
	#define COLOR_SEAGREEN 		0x2C4A
	#define COLOR_SEASHELL 		0xFFBD
	#define COLOR_SIENNA 		0xA285
	#define COLOR_SILVER 		0xC618
	#define COLOR_SKYBLUE 		0x867D
	#define COLOR_SLATEBLUE 	0x6AD9
	#define COLOR_SLATEGRAY 	0x7412
	#define COLOR_SNOW 			0xFFDF
	#define COLOR_SPRINGGREEN 	0x07EF
	#define COLOR_STEELBLUE 	0x4416
	#define COLOR_TAN 			0xD5B1
	#define COLOR_TEAL			0x0410
	#define COLOR_THISTLE 		0xDDFB
	#define COLOR_TOMATO 		0xFB08
	#define COLOR_TURQUOISE 	0x471A
	#define COLOR_VIOLET 		0xEC1D
	#define COLOR_WHEAT 		0xF6F6
	#define COLOR_WHITE 		0xFFFF
	#define COLOR_WHITESMOKE 	0xF7BE
	#define COLOR_YELLOW 		0xFFE0
	#define COLOR_YELLOWGREEN 	0x9E66

	const u_int colores[140] = {  COLOR_ALICEBLUE,	//arreglo para el facil acceso a los colores por alfabeto
			 COLOR_ANTIQUEWHITE,
			 COLOR_AQUA,
			 COLOR_AQUAMARINE,
			 COLOR_AZURE,
			 COLOR_BEIGE,
			 COLOR_BISQUE,
			 COLOR_BLACK,
			 COLOR_BLANCHEDALMOND,
			 COLOR_BLUE,
			 COLOR_BLUEVIOLET,
			 COLOR_BROWN,
			 COLOR_BURLYWOOD,
			 COLOR_CADETBLUE,
			 COLOR_CHARTREUSE,
			 COLOR_CHOCOLATE,
			 COLOR_CORAL,
			 COLOR_CORNFLOWERBLUE,
			 COLOR_CORNSILK,
			 COLOR_CRIMSON,
			 COLOR_CYAN,
			 COLOR_DARKBLUE,
			 COLOR_DARKCYAN,
			 COLOR_DARKGOLDENROD,
			 COLOR_DARKGRAY,
			 COLOR_DARKGREEN,
			 COLOR_DARKKHAKI,
			 COLOR_DARKMAGENTA,
			 COLOR_DARKOLIVEGREEN,
			 COLOR_DARKORANGE,
			 COLOR_DARKORCHID,
			 COLOR_DARKRED,
			 COLOR_DARKSALMON,
			 COLOR_DARKSEAGREEN,
			 COLOR_DARKSLATEBLUE,
			 COLOR_DARKSLATEGRAY,
			 COLOR_DARKTURQUOISE,
			 COLOR_DARKVIOLET,
			 COLOR_DEEPPINK,
			 COLOR_DEEPSKYBLUE,
			 COLOR_DIMGRAY,
			 COLOR_DODGERBLUE,
			 COLOR_FIREBRICK,
			 COLOR_FLORALWHITE,
			 COLOR_FORESTGREEN,
			 COLOR_FUCHSIA,
			 COLOR_GAINSBORO,
			 COLOR_GHOSTWHITE,
			 COLOR_GOLD,
			 COLOR_GOLDENROD,
			 COLOR_GRAY,
			 COLOR_GREEN,
			 COLOR_GREENYELLOW,
			 COLOR_HONEYDEW,
			 COLOR_HOTPINK,
			 COLOR_INDIANRED,
			 COLOR_INDIGO,
			 COLOR_IVORY,
			 COLOR_KHAKI,
			 COLOR_LAVENDER,
			 COLOR_LAVENDERBLUSH,
			 COLOR_LAWNGREEN,
			 COLOR_LEMONCHIFFON,
			 COLOR_LIGHTBLUE,
			 COLOR_LIGHTCORAL,
			 COLOR_LIGHTCYAN ,
			 COLOR_LIGHTGOLDENRODYELLOW,
			 COLOR_LIGHTGREEN,
			 COLOR_LIGHTGREY,
			 COLOR_LIGHTPINK,
			 COLOR_LIGHTSALMON,
			 COLOR_LIGHTSEAGREEN,
			 COLOR_LIGHTSKYBLUE,
			 COLOR_LIGHTSLATEGRAY,
			 COLOR_LIGHTSTEELBLUE,
			 COLOR_LIGHTYELLOW,
			 COLOR_LIME,
			 COLOR_LIMEGREEN,
			 COLOR_LINEN,
			 COLOR_MAGENTA,
			 COLOR_MAROON,
			 COLOR_MEDIUMAQUAMARINE,
			 COLOR_MEDIUMBLUE,
			 COLOR_MEDIUMORCHID,
			 COLOR_MEDIUMPURPLE,
			 COLOR_MEDIUMSEAGREEN,
			 COLOR_MEDIUMSLATEBLUE,
			 COLOR_MEDIUMSPRINGGREEN,
			 COLOR_MEDIUMTURQUOISE,
			 COLOR_MEDIUMVIOLETRED,
			 COLOR_MIDNIGHTBLUE,
			 COLOR_MINTCREAM,
			 COLOR_MISTYROSE ,
			 COLOR_MOCCASIN,
			 COLOR_NAVAJOWHITE,
			 COLOR_NAVY	,
			 COLOR_OLDLACE,
			 COLOR_OLIVE,
			 COLOR_OLIVEDRAB,
			 COLOR_ORANGE,
			 COLOR_ORANGERED,
			 COLOR_ORCHID,
			 COLOR_PALEGOLDENROD,
			 COLOR_PALEGREEN,
			 COLOR_PALETURQUOISE,
			 COLOR_PALEVIOLETRED,
			 COLOR_PAPAYAWHIP,
			 COLOR_PEACHPUFF,
			 COLOR_PERU,
			 COLOR_PINK,
			 COLOR_PLUM,
			 COLOR_POWDERBLUE,
			 COLOR_PURPLE,
			 COLOR_RED,
			 COLOR_ROSYBROWN,
			 COLOR_ROYALBLUE,
			 COLOR_SADDLEBROWN,
			 COLOR_SALMON,
			 COLOR_SANDYBROWN,
			 COLOR_SEAGREEN,
			 COLOR_SEASHELL ,
			 COLOR_SIENNA,
			 COLOR_SILVER,
			 COLOR_SKYBLUE,
			 COLOR_SLATEBLUE,
			 COLOR_SLATEGRAY,
			 COLOR_SNOW,
			 COLOR_SPRINGGREEN,
			 COLOR_STEELBLUE,
			 COLOR_TAN ,
			 COLOR_TEAL,
			 COLOR_THISTLE,
			 COLOR_TOMATO,
			 COLOR_TURQUOISE,
			 COLOR_VIOLET,
			 COLOR_WHEAT,
			 COLOR_WHITE,
			 COLOR_WHITESMOKE,
			 COLOR_YELLOW,
			 COLOR_YELLOWGREEN }; //140

#endif /* COLORES_H_ */
